# Generated by Django 6.1 on 2026-09-04 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_report_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('Waste Dumping', 'Illegal Waste Dumping'), ('Land Clearance', 'Land Clearance'), ('Stagnant Water', 'Stagnant Water')], default='Waste Dumping', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('off_duty', 'Off Duty')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Inspection', 'Under Inspection'), ('Verified', 'Verified'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landowner_name', models.CharField(max_length=200)),
                ('landowner_contact', models.CharField(blank=True, max_length=20)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Notice Issued', 'Notice Issued'), ('Pending', 'Pending'), ('Complied', 'Complied'), ('Non-Complied', 'Non-Complied')], default='Notice Issued', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='watch.report')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_status', models.CharField(choices=[('Verified', 'Verified'), ('Not Verified', 'Not Verified'), ('Requires Action', 'Requires Action')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('inspected_date', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='watch.report')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Waste Removal', 'Waste Removal'), ('Land Clearance', 'Land Clearance'), ('Stagnant Water Removal', 'Stagnant Water Removal')], max_length=40)),
                ('status', models.CharField(choices=[('Pending Assignment', 'Pending Assignment'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rework', 'Rework')], default='Pending Assignment', max_length=30)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='watch.report')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
