# Generated by Django 6.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(
                choices=[
                    ('Waste Dumping', 'Illegal Waste Dumping'),
                    ('Land Clearance', 'Overgrown Vegetation / Land Clearance'),
                    ('Stagnant Water', 'Stagnant Water Removal'),
                ],
                default='Waste Dumping',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
