# Generated by Django 6.1 on 2026-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_update_report_issue_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/after/'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/before/'),
        ),
    ]
